module.exports = function(grunt) {

    grunt.initConfig({
        pkg: grunt.file.readJSON('package.json'),

        // Babel: Transpiles ES6 to ES5 and converts to AMD format
        babel: {
            options: {
                sourceMap: false,
                presets: ['@babel/preset-env'],
                plugins: ['@babel/plugin-transform-modules-amd']
            },
            dist: {
                files: [{
                    expand: true,
                    cwd: 'amd/src',         
                    src: ['*.js'],          
                    dest: 'amd/build',      
                    ext: '.js'
                }]
            }
        },

        // Uglify: Minifies the file generated by Babel
        uglify: {
            options: {
                banner: '/*! <%= pkg.name %> <%= grunt.template.today("yyyy-mm-dd") %> */\n'
            },
            build: {
                files: [{
                    expand: true,
                    cwd: 'amd/build',      
                    src: ['*.js', '!*.min.js'], 
                    dest: 'amd/build',      
                    ext: '.min.js'          
                }]
            }
        },

        // Watch: Monitors changes to compile automatically
        watch: {
            scripts: {
                files: ['amd/src/*.js'],
                tasks: ['default'],
                options: {
                    spawn: false,
                    event: ['all'] 
                },
            },
        }
    });

    grunt.loadNpmTasks('grunt-babel');
    grunt.loadNpmTasks('grunt-contrib-uglify');
    grunt.loadNpmTasks('grunt-contrib-watch');

    // Registers the 'amd' task that you defined in package.json
    grunt.registerTask('amd', ['babel', 'uglify']);
    
    // Default task
    grunt.registerTask('default', ['amd']);
};
